/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations, useVideoTexture } from '@react-three/drei';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

const DemoComputer = (props) => {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('./models/computer.glb');
    const { actions } = useAnimations(animations, group);

    const txt = useVideoTexture(props.texture ? props.texture : './textures/project/project1.mp4');

    useEffect(() => {
        if (txt) {
            txt.flipY = false;
        }
    }, [txt]);

    useGSAP(() => {
        gsap.from(group.current.rotation, {
            y: Math.PI / 2,
            duration: 1,
            ease: 'power3.out',
        });
    }, [txt]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="monitor-screen"
                    // castShadow
                    // receiveShadow
                    geometry={nodes['monitor-screen'].geometry}
                    material={nodes['monitor-screen'].material}
                    position={[0.127, 1.831, 0.511]}
                    rotation={[1.571, -0.005, 0.031]}
                    scale={[0.661, 0.608, 0.401]}>
                    <meshBasicMaterial map={txt} toneMapped={false} />
                </mesh>
                <group name="RootNode" position={[0, 1.093, 0]} rotation={[-Math.PI / 2, 0, -0.033]} scale={0.045}>
                    <group
                        name="Screen001"
                        position={[5.658, 1.643, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen002"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen003"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen004"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen005"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen006"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen007"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen008"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen009"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen010"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen011"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen012"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen013"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen014"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen015"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen016"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen017"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen018"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen019"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen020"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen021"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen022"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen023"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen024"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen025"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen026"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen027"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen028"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen029"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen030"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen031"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen032"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen033"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen034"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen035"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen036"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen037"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen038"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen039"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen040"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen041"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen042"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen043"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen044"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen045"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen046"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen047"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Screen048"
                        position={[5.658, 1.644, 0.812]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.923, 0.855, 0.855]}
                    />
                    <group
                        name="Tower-light-007"
                        position={[16.089, -3.47, -14.495]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.963}
                    />
                    <group
                        name="Tower-light-008"
                        position={[15.155, -3.47, -14.495]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.963}
                    />
                </group>
                <group
                    name="Monitor-B-_computer_0"
                    position={[0.266, 1.132, 0.051]}
                    rotation={[0, -0.033, 0]}
                    scale={[0.042, 0.045, 0.045]}>
                    <mesh
                        name="Monitor-B-_computer_0_1"
                        // castShadow
                        // receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_1'].geometry}
                        material={materials.computer}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_2"
                        // castShadow
                        // receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_2'].geometry}
                        material={materials.base__0}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_3"
                        // castShadow
                        // receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_3'].geometry}
                        material={materials.Material_36}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_4"
                        // castShadow
                        // receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_4'].geometry}
                        material={materials.Material_35}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_5"
                        // castShadow
                        // receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_5'].geometry}
                        material={materials.Material_34}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_6"
                        // castShadow
                        // receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_6'].geometry}
                        material={materials.keys}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_7"
                        // castShadow
                        // receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_7'].geometry}
                        material={materials.keys2}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_8"
                        // castShadow
                        // receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_8'].geometry}
                        material={materials.Material_37}
                    />
                </group>
            </group>
        </group>
    );
};

useGLTF.preload('./models/computer.glb');

export default DemoComputer;